### ISSUE TITLE
type *zip.Writer has no field or method SetOffset

### ISSUE THREAD

**Issue by tekstrand** [GeertJohan/go.rice#103]
`github.com/GeertJohan/go.rice/rice/append.go:62: zipWriter.SetOffset undefined (type *zip.Writer has no field or method SetOffset)`

Clean install on a raspberry pi, go version go1.3.3 linux/arm

**Comment by EvanPurkhiser** [comment]
What version of golang are you using? See https://github.com/GeertJohan/go.rice/pull/87

**Comment by tekstrand** [comment]
@EvanPurkhiser I'll give it a try, I've been using master so I'm not sure why that wouldn't be in there

**Comment by EvanPurkhiser** [comment]
You need go 1.5+ for the the `SetOffset` method to exist.

**Comment by GeertJohan** [comment]
go1.3.3 is very old, please update to a recent version.
