### ISSUE TITLE
go:generate examples

### ISSUE THREAD

**Issue by boyska** [GeertJohan/go.rice#109]
tools like this have most of their value when integrated with `go generate` mechanism.

Documentation should provide simple examples on how to do that.

**Comment by iand** [comment]
:+1:

It's as simple as putting a line like `//go:generate rice embed-go` into one source file in a package.

**Comment by boyska** [comment]
I know. However, the doc should say that.

**Comment by GeertJohan** [comment]
There's a whole list of build strategies and tools. Instead of recommending a certain tool, I leave this open to the imagination of the user as not to give the impression that it should be used with a specific tool.
