### ISSUE TITLE
FindBox from subfolder?

### ISSUE THREAD

**Issue by painhardcore** [GeertJohan/go.rice#111]
Trying to make embedded files from "build" folder at $GOPATH/src/yourApplication/frontend/build  with rice.MustFindBox. 
It works only if I move build folder to application folder - $GOPATH/src/yourApplication/build , then rice.MustFindBox("build") works. 
Tried rice.MustFindBox("build") and rice.MustFindBox("frontend/build") but no luck.

**Comment by GeertJohan** [comment]
I'm think `rice.MustFindBox("frontend/build")` should work. Please let me know if it doesn't and what error you get?
