### ISSUE TITLE
Add an option to exit cleanly if executable was already appended

### ISSUE THREAD

**Issue by ainar-g** [GeertJohan/go.rice#123]
Since Go 1.10 `go build` doesn't rebuild the executable if nothing changed. This is good, but in my Makefile I have this:

```make
build:
	$(GO) build -o bin/binary my/binary.go
	rice -i my/assets append --exec=bin/binary
```

Which fails if I call `make build` twice, because:

```
Cannot append to already appended executable. Please remove bin/binary and build a fresh one.
```

Of course I can do something like `|| exit 0` in the Makefile, but that would mean that actual errors will be ignored as well. Removing the binary before every build is what I do now, but that means that I effectively ignore Go 1.10 build caching. If there was a flag that makes rice write something to stderr and exit with 0 in such cases, that would be perfect.

Thoughts?

**Comment by GeertJohan** [comment]
Hi ainar-g. I don't think this is something that should be added to the rice command.
I think there are two things you can do here:
Either match on the output text and ignore when it has that "Cannot append to already appended executable" error string. Or take a fingerprint (sha256sum) of the binary before and after go build. Append when the fingerprints are not equal.
