### ISSUE TITLE
exec reply an error

### ISSUE THREAD

**Issue by yanyuxuanz** [GeertJohan/go.rice#124]
./rice.exe append --exec E:/goes/src/gosciter/main.exe
no calls to rice.FindBox() or rice.MustFindBox() found in import path `github.com/GeertJohan/go.rice/rice`

**Comment by GeertJohan** [comment]
Perhaps you have not used a constant string in your rice.FindBox call? Or try using `--import-path` to point `rice.exe` to the right package.
