### ISSUE TITLE
file can not be found on windows!

### ISSUE THREAD

**Issue by lanybass** [GeertJohan/go.rice#125]
I traced the code ,found the reason:
when generate the go-embed, the **"\\"** in file name has been replaced to **"/"**
https://github.com/GeertJohan/go.rice/blob/c02ca9a983da5807ddf7d796784928f5be4afd09/rice/embed-go.go#L73

but when walk the assets, it find name with **filepath.Join(path, name)**
https://github.com/GeertJohan/go.rice/blob/c02ca9a983da5807ddf7d796784928f5be4afd09/walk.go#L63

so it can't find the file "admin\\index.tmpl" by walk.go on windows,cause it's "admin/index.tmpl" in rice-box no matter on linux or windows.

**Comment by npotts** [comment]
@lanybass: per the [filepath docs](https://golang.org/pkg/path/filepath/), a forward slash *should* be in use - I can verify that on Windows, if you use forward slashes, things do work as expected.

**Comment by GeertJohan** [comment]
Yes, it should work when using the forward slash.
