### ISSUE TITLE
Error test rice

### ISSUE THREAD

**Issue by nicolasStevenin** [GeertJohan/go.rice#127]
Hi,

When I test your project, I have this error :
**command: go test -buildmode pie -compiler gc -ldflags "-X github.com/GeertJohan/go.rice/version.commit=c02ca9a983da5807ddf7d796784928f5be4afd09 -X github.com/GeertJohan/go.rice/version=0 -extldflags '-Wl,-z,relro  '"**

github.com/GeertJohan/go.rice/rice
./find.go:83:7: variableToRemember declared but not used
vet: typecheck failures

Thanks

**Comment by GeertJohan** [comment]
Thanks, I've removed the unused variable.
