### ISSUE TITLE
 ignore generated files

### ISSUE THREAD

**Issue by arnottcr** [GeertJohan/go.rice#136]
## description
`rice` includes all files from requested `FindBox` directory, I noticed in #135 this can become problematic if generated files or binaries get accidentially included.

While #37/#83 or #47 could help with this, it feels pretty straight forward to at least exclude the rules from `rice clean`.

**Comment by GeertJohan** [comment]
This could work indeed. Would you be willing to create a PR for this?

**Comment by arnottcr** [comment]
Happily, I think the low hanging fruit is the rice generated files, and that should not be too hard.

Detecting go binaries could lead to false positives, so if you have any ideas let me know.
