### ISSUE TITLE
Possible to pack SQLite file?

### ISSUE THREAD

**Issue by TangMonk** [GeertJohan/go.rice#145]
I have a program that read data from local sqlite db, and show data to users, I wanna to pack all assets include sqlite file to one binary file, this program only execute read operation from sqlite, is it possible to pack sqlite file?

**Comment by GeertJohan** [comment]
That should be possible. You'll either have to give the file contents directly to sqlite lib(if thats even possible), or write the file to disk/tmp folder and start sqlite with that file.
