### ISSUE TITLE
Getting rice-box.go file with byte Array instead of string.

### ISSUE THREAD

**Issue by karliatto** [GeertJohan/go.rice#161]
I am running `rice embed-go` in project [lnme](https://github.com/bumi/lnme) with go version `go version go1.15.3 linux/amd64`

When I run `rice embed-go`, it creates a `rice-box.go` that contains `Content` with a an array of bytes instead of just a string with the html code.

```go
file2 := &embedded.EmbeddedFile{
		Filename:    `index.html`,
		FileModTime: time.Unix(1603709268, 0),
		Content:     string([]byte{0x3c, 0x21, 0x44, 0x4f, 0x43, 0x54, 0x59, 0x50, 0x45, 0x20, 0x68, 0x74, 0x6d, 0x6c, 0x3e, 0xa, 0x3c, 0x68, 0x74, 0x6d, 0x6c, 0x20, 0x6c, 0x61, 0x6e, 0x67, 0x3d, 0x22, 0x65, 0x6e, 0x22, 0x3e, 0xa, 0x20, 0x20, 0x3c, 0x68, 0x65, 0x61, 0x64, 0x3e, 0xa, 0x20, 0x20, 0x20, 0x20, 0x3c, 0x6d, 0x65, 0x74, 0x61, 0x20, 0x63, 0x68, 0x61, 0x72, 0x73, 0x65, 0x74, 0x3d, 0x22, 0x55, 0x54, 0x46, 0x2d, 0x38, 0x22, 0x3e, 0xa, 0x20, 0x20, 0x20, 0x20, 0x3c, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x3e, 0xe2, 0x9a, 0xa1, 0x20, ...
....
```
intead of:

```go
file2 := &embedded.EmbeddedFile{
		Filename:    "index.html",
		FileModTime: time.Unix(1603706396, 0),

		Content: string("<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\">\n    <title>⚡ Send me some Sats</title>\n    <style>\n      html {\n        width: 100%;\n        height: 100%;\n        font-size: 1vw;\n      }\n      body {\n        background-image: linear-gradient(60deg, #3d3393 0%, #2b76b9 37%, #2cacd1 65%, #35eb93 100%);\n        font-family: \"Lucida Sans Unicode\", \"Lucida Grande\", sans-serif;\n      }\n      .wrapper {\n        font-weight: 400;\n        line-height: 1.25
```

I am not sure if I am running it with wrong arguments but I do not see much possible configuration for `rice embed-go`. 

Any advice? 

Thanks.

**Comment by GeertJohan** [comment]
Hi @karliatto 
The byte array contains the same characters as the string you need, it is then converted to a string and stored in the Content field.
`string([]byte{0x41, 0x42, 0x43, 0x44}) == "ABCD"`
The HTML is really there, just written as bytes. If you use the box, it should give you the HTML you embedded.

Please feel free to re-open this issue if you have further questions.

**Comment by GeertJohan** [comment]
You may be wondering why it is so complicated. The reason is that not all bytes can be safely expressed in text characters (UTF-8) and that complicated escape sequences are required to make string embedding safe. For example, instead of HTML you could embed an image, how would we safely write those bytes as a string? There are also performance considerations. That's why the text file is embedded through a byte slice.
