### ISSUE TITLE
`Bytes()` doesn't act like `Open()` + `ReadAll()`

### ISSUE THREAD

**Issue by abourget** [GeertJohan/go.rice#45]
Under Windows, I'm getting some `The handle is invalid.` when trying to access some files using `.Bytes()`.  Using `Open()` and reading its content is ok.  Why wouldn't `Bytes()` just do that, and wrap those two calls ?

I've proposed a fix in https://github.com/GeertJohan/go.rice/pull/44

It fails when we call `zipFile.Open` here https://github.com/GeertJohan/go.rice/blob/master/box.go#L266

Apparently, `Open()` doesn't need to do that.. but stil gets the file contents.

**Comment by abourget** [comment]
ping ?

**Comment by GeertJohan** [comment]
I think we can Bytes() implementation with your ReadFile() implementation. This won't break any functionality, but might cause a few more allocs when reading an embedded file.
Can you create a new PR replacing the ReadFile() implementation?

By the way: I'm still wondering where that `The handle is invalid.` error is comming from..

**Comment by abourget** [comment]
the culprit is the call to `zipFile.Open` which returns an Error that has, as only string `The handle is invalid.` .. I'd like to know more myself :)   I read somewhere that `(a) 'invalid handle' in progammers terms means an attempt to open a file with low-level read capability failed` (http://www.techspot.com/community/topics/the-handle-is-invalid-whats-that-mean.29228/ ..)

I could do some extensive debugging, but since ReadFile does work.. I'm wondering if any optimizations in `Bytes()` are worth it..

I'll make a new PR with `ReadFile()` replacing `Bytes()`.. it also has the advantage to be easier to follow

**Comment by GeertJohan** [comment]
#44 was merged, thanks again :)
