### ISSUE TITLE
Mixed file storage

### ISSUE THREAD

**Issue by swynter-ladbrokes** [GeertJohan/go.rice#59]
Say I have a box that was built with

box/test.html

I've built my binary, and I've got

``` go
    rice := rice.Config{
        LocateOrder: []rice.LocateMethod{rice.LocateFS, rice.LocateEmbedded},
    }

    box, _ := rice.FindBox("box")

    http.Handle("/", http.FileServer(box.HTTPBox())
    go func()
        _ = http.ListenAndServe(":8080", nil)
    }()

    select {}
```

I can call localhost:8080/test.html just fine
but if I create a directory 'box' and add 'test2.html' to it (and restart the binary)
I can no longer call localhost:8080/test.html

**Comment by GeertJohan** [comment]
Sorry for the late reply. In your second example you're using a box with two files in it `test.html` and `test2.html`. Correct? I've never seen this kind of behavior before. Are you still having this issue?
