### ISSUE TITLE
Vendoring binaries

### ISSUE THREAD

**Issue by noonien** [GeertJohan/go.rice#60]
I use [go.rice](github.com/GeertJohan/go.rice) to embed static files into my binaries and would like to vendor the rice main package.

I already did this using vendor add github.com/GeertJohan/go.rice/rice and the package was successfully vendored, however, the package status is listed as "unused".

I figure this is because the package is not imported anywhere, nor could it be.

Would it perhaps be a good idea to consider packages that are named "main" as internal and pull their dependencies as well when vendoring them?

**Comment by GeertJohan** [comment]
This sounds like it has more to do with your vendoring tool. I assume it checks if vendored packages are used?

What tool are you using?

**Comment by noonien** [comment]
Ah, I apologize, I've filed the issue to the wrong repository.

**Comment by GeertJohan** [comment]
No problem!
