### ISSUE TITLE
Can a default base drectory be set instead of using the full source path

### ISSUE THREAD

**Issue by osiloke** [GeertJohan/go.rice#61]
This would be helpful if you distribute binaries of your app but don't want to embed resources to the binary file.

**Comment by GeertJohan** [comment]
I think this could be added in v2. Please see https://github.com/GeertJohan/go.rice/issues/47.
Maybe you can work out how this would work in v2 and the Ricefile, and comment on that issue?

**Comment by osiloke** [comment]
Will do
