### ISSUE TITLE
template.ParseFiles

### ISSUE THREAD

**Issue by zaz600** [GeertJohan/go.rice#70]
how to use rice with template ParseFiles?
i need template inheritance

**Comment by lmas** [comment]
You can't use `ParseFiles` as that loads files directly from the filesystem. You have to manually iterate over the templates and load them yourself. See #71 for an example that I've been using and watch out for that bug I found.

**Comment by zaz600** [comment]
i use ParseFiles to get one template from 2 or more

```
	post_template  = template.Must(template.ParseFiles(path.Join("templates", "layout.html"), path.Join("templates", "post.html")))
	error_template = template.Must(template.ParseFiles(path.Join("templates", "layout.html"), path.Join("templates", "error.html")))
```

are you doing the same in https://github.com/GeertJohan/go.rice/issues/71 ?

**Comment by lmas** [comment]
My templates depends on my `base.html` template which would be equal to your `layout.html` so yes, I also create templates out of 2 or more files (with inheritance).

I guess you could do it like this:

    tbox := rice.MustFindBox("templates")
    post_template = template.Must(template.Parse(tbox.String("layout.html") + tbox.String("post.html")))

Note that you can't use `ParseFiles` with go.rice.

**Comment by zaz600** [comment]
Thank you. I will try it!
