### ISSUE TITLE
Infinite loop with File.Readdir()

### ISSUE THREAD

**Issue by lmas** [GeertJohan/go.rice#75]
Edit: cleaned up the whole issue...

The documentation for [`os.File.Readdir(n)`](https://golang.org/pkg/os/#File.Readdir) states that when n > 0, `Readdir()` must return a `io.EOF` at the end of the directory.
[`rice.File.Readdir()`](https://github.com/GeertJohan/go.rice/blob/master/file.go#L70) doesn't comform to this behavior, for appended files and dirs, and so we will enter an infinite loop in https://golang.org/src/net/http/fs.go#L70 when we try to serve appended files with `http.FileServer` and `rice.box.HTTPBox()`.

~~I'm afraid that `rice.File.Readdir()` needs to be rewritten so it instead will work over multiple calls (for example: first call returns all files/dirs in current dir, second call returns `io.EOF` to end the loop). But that means it needs to save some kind of state and shit, so it would be a pretty big change...~~
Edit: Nvm, I finally noticed you already got it figured out, for embedded files at least.

**Comment by GeertJohan** [comment]
Duplicated by #108. Work is being done in that issue to solve this bug. Thanks for reporting!
