### ISSUE TITLE
box lists its contents but should not

### ISSUE THREAD

**Issue by markfink** [GeertJohan/go.rice#76]
thanks for sharing this code. Is is very helpful.

Not sure if it matters, I used "rice embed-syso" to create the box.
There is one thing that is a little bit disturbing for me. Every time I run the code the box prints out all the contents to the console. I have not yet found out why it does that. I think the expected behavior for packages is to "shut up" or return an error?

This is how I use the box:

```
box := rice.MustFindBox("web")
appFileServer := http.FileServer(box.HTTPBox())
```

Any chance that this configurable?

**Comment by GeertJohan** [comment]
`embed-syso` is not stable yet, and should not be used. I'm not sure if it ever will become stable. Please use the `embed-go` or `append` strategies.
