### ISSUE TITLE
ignore option missing

### ISSUE THREAD

**Issue by hryamzik** [GeertJohan/go.rice#80]
Here's how it works with both `go-bindata` and `go-bindata-assetfs`:

```
go-bindata-assetfs -ignore=\.DS_Store
```

**Comment by vjeantet** [comment]
+1

**Comment by GeertJohan** [comment]
Actually #83 is a duplicate of this issue. But there has been more discussion in that issue so I'm closing this one. This is a good feature request thought, thanks for sending it in!
