### ISSUE TITLE
Serving multiple sub-directories at root level

### ISSUE THREAD

**Issue by smithjessk** [GeertJohan/go.rice#85]
I want to serve the following static folder. However, I would like, e.g., the files `foo.json` and `all.html` to be available via `/foo.json` and `/all.html`. Is there currently a way to do this with Rice? 

```
[jess@localhost assets]$ tree -L 2
.
├── frontend
│   └── foo.json
└── iframes
    ├── all.html
    ├── css
    ├── img
    ├── js
    └── lib

6 directories, 2 files
```

If not, I propose implementing a way to "join" boxes and create a new box. If you're on-board, I would be happy to implement this myself.

Thanks!

**Comment by GeertJohan** [comment]
Hi. I think this should not be done by rice, but instead by a custom http handler that first checks box frontend, then box iframe. Or if it's currently the same box with two directories, first check directory A, then B.
