### ISSUE TITLE
Append work on windows

### ISSUE THREAD

**Issue by Ducatel** [GeertJohan/go.rice#88]
Hi everybody,

I have try to make an `append` on windows and it's working.
```go
package main
import (
	"fmt"
	"github.com/GeertJohan/go.rice"
)

func main() {
	assetsBox, err := rice.FindBox("assets/")
	if err != nil {
		panic("oups")
	}
	content, _ := assetsBox.String("plop.txt")
	fmt.Println(content)
}
```
The directory structure 
```
- /
   - main.go
   - Assets/
      - plop.txt
```

And I have try with that command
```
go build
rice append /exec app.exe

#### WARNING ! ####
rice append` is known not to work under windows because the `zip` command is not available. Please let me know if you got this to work (and how).
```

When I execute the binary (in place, in a different folder, in different computer) it show the content of `plop.txt` file like expected.

So it's seems to work

PS: I'm under windows 10 without zip available in command line

**Comment by Ducatel** [comment]
I have also try to add files in windows executable from a linux docker image and it's working.
But it's working if you didn't have `zip` in PATH.

Step to reproduce 
```
docker run -ti --rm -v "%CD%:/usr/src/app" -w "/usr/src/app" golang:wheezy bash
> cp MyApp.exe MyApp.exe.bak
> go get github.com/GeertJohan/go.rice/rice
> rice append /exec MyApp.exe
Error setting zip offset: exec: "zip": executable file not found in $PATH
> echo $?
1
> mv MyApp.exe MyApp.withoutZip.exe
> cp MyApp.exe.bak MyApp.exe
> apt-get update && apt-get install -y  zip
> rice append /exec MyApp.exe // This command destroy the binary and generate some broken file
Error setting zip offset: exit status 15
> echo $?
1
```

So I that example `MyApp.withoutZip.exe` work as expected on windows host

Note: in the current directory I put:
* The windows executable
* The go file which have call to `rice` API
* The folder with my static files

**Comment by GeertJohan** [comment]
Using zip as a program has been dropped by #87, we're now using the SetOffset feature introduced in go1.5
