### ISSUE TITLE
Filenames containing backtick are not escaped properly

### ISSUE THREAD

**Issue by nkovacs** [GeertJohan/go.rice#95]
Although unlikely, it's valid for a filename to contain a backtick, which would result in an invalid go file.

I have a fix in https://github.com/nkovacs/go.rice/tree/filename-quote, but it depends on #93 for tests.

**Comment by nkovacs** [comment]
Another (even more unlikely) issue: it's possible for a filename to contain a newline, which will break the `// {{.Filename}}` part, since the generated code will look like this:

```
		ChildFiles:  []*embedded.EmbeddedFile{
			filec, // new
line
			filed, // test1.txt
			filee, // test2.txt
			
		},
```

**Comment by GeertJohan** [comment]
I'd be happy to take that as a PR!

**Comment by GeertJohan** [comment]
Thanks, I've merged it.
