### ISSUE TITLE
File does not exist on Windows Platform

### ISSUE THREAD

**Issue by tscs37** [GeertJohan/go.rice#99]
When walking an embedded box on a windows platform, the error `file does not exist` is returned due to a wrong slash.

The file in question is accessed via the `\` slash, not via the `/` slash that is generated from the rice tool (on windows and linux equally).

**Comment by tscs37** [comment]
The issue is reproducible with the installer from https://github.com/tscs37/discord.mods/tree/master/installer

The file `build.sh` is used to build the entire project and then the installer, the resulting binary does not work on windows.

**Comment by rskumar** [comment]
I too started getting this problem today.

**Comment by GeertJohan** [comment]
I would need to investigate this, but I don't have a windows machine at my disposal to reproduce.. Could anyone point down the exact problem and perhaps propose a fix?

**Comment by tscs37** [comment]
As far as I've been able to investigate so far, the problem is that go.rice relies on the os.PathSeperator when accessing the box.

So when the box is generated on a linux system, it'll generate it using forward slashes, the resulting file is not portable. To be able to generate a windows box, one must build rice under windows and generate the box under windows, then compile the entire project on windows or using the windows specific box as source.

One example line that has an issue like this would be [walk.go#L63](https://github.com/GeertJohan/go.rice/blob/9fdfd46f9806a9228aae341d65ab75c5235c383c/walk.go#L63), hte filepath.Join does not work if the internal path uses slashes differing to the OS one.

I suggest that the box could internally use a unix slash and translate the slash using filepath.FromSlash (IIRC this is the correct one) into the one suitable for the current operating system. That makes it far more portable.

To be able to join filepaths, the .ToSlash and .FromSlash functions can be used to translate to OS specific, use .JoinPath and translate back (this is a bit hacky but preserves the usage of filepath.Join)

**Comment by rskumar** [comment]
Anyone looking into this issue?

**Comment by producerism** [comment]
Fix should be fairly easy, since it appears to be limited to this small block of code

https://github.com/GeertJohan/go.rice/blob/master/walk.go#L29-L36

**Comment by rskumar** [comment]
I don't have access to Windows platform now. I think using `path.Join(...)` will be a better approach, and should fix this.
Yet to validate.

**Comment by pzeinlinger** [comment]
I've just come across this issue. Cross compiling Windows binaries on Linux does not work as expected. Files in the root folder of the box work perfectly fine, however, the walk function does not descent into subfolders. Is there any progress towards a solution?
